[package]
name = "e6502"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = {workspace = true}
console = {workspace = true}
phf = {workspace = true}
sdl2 = {workspace = true}
either = "1.15.0"
rustyline = "15.0.0"
